### PR TITLE
Updating TJPCov to require python >= 3.8

### LINKED ISSUE #85: Require python 3.8
SACC would like to update to require python 3.8 or above.  Currently we require 3.7, but I don't think 3.8 would break anything.

### PR DESCRIPTION
**Pull request by mattkwiecien**
Closes #85 

All tests pass. Also tested 3.9, 3.10, and 3.11.

Would be nice to include in our CI build tests for 3.9, 3.10, and 3.11 to ease future upgrades.

### CODE REVIEW

**Comment by mattkwiecien** [comment]
New sacc version broke some tests 🤣

**Comment by mattkwiecien** [comment]
Should be fixed!

**Comment by joezuntz** [comment]
Sorry!

**Comment by mattkwiecien** [comment]
Pushed a new v0.4.0 tag on this branch for new PyPI release.  Lmk if we would rather do a patch, but requiring a new python version does seem like a "minor" update more than a patch

**Comment by carlosggarcia** [comment]
Based on https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api  and https://softwareengineering.stackexchange.com/questions/345335/semantic-version-change-to-application-when-upgrading-libraries-involved, I'd say it's a patch since the user has not seen any change and we are fixing a bug in our code (introduced by the library update).

**Review by carlosggarcia — APPROVED** [review]
LGTM!

**Pull request merged**
